#!/bin/sh
# Generated by OpenWrt Custom Firmware Builder
# Template: packages.sh

# BEGIN_VARIABLE_DEFINITIONS
# PACKAGES=""
# LANG_PACKAGES=""
# END_VARIABLE_DEFINITIONS

# Detect package manager
if command -v opkg >/dev/null 2>&1; then
    PKG_MGR=opkg
    opkg update
elif command -v apk >/dev/null 2>&1; then
    PKG_MGR=apk
    apk update
else
    echo 'Error: No supported package manager found'
    exit 1
fi

# Install language packages
if [ -n "$LANG_PACKAGES" ]; then
    echo "Installing language packages..."
    [ "$PKG_MGR" = "opkg" ] && opkg install $LANG_PACKAGES
    [ "$PKG_MGR" = "apk" ] && apk add $LANG_PACKAGES
fi

# Install selected packages
if [ -n "$PACKAGES" ]; then
    echo "Installing selected packages..."
    [ "$PKG_MGR" = "opkg" ] && opkg install $PACKAGES
    [ "$PKG_MGR" = "apk" ] && apk add $PACKAGES
fi

exit 0
